### ISSUE TITLE
More function categories into _pkgdown.yml 

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#776]
There is a large list of [cache functions](https://ropensci.github.io/drake/reference/index.html#section-cache-utilities) on the `pkgdown` site. The list comes from `_pkgdown.yml`.

https://github.com/ropensci/drake/blob/13c171345477450bd03fafb0f959774ce6e2a57a/_pkgdown.yml#L100-L120

I think we can split these up into more categories. We can change the "Cache utilities" section of `_pkgdown.yml` to the following.

```
- title: Caches
  contents:
  - '`get_cache`'
  - '`new_cache`'
  - '`find_cache`'
- title: Cache reading
  contents:
  - '`loadd`'
  - '`readd`'
  - '`cached`'
  - '`drake_cache_log`'
  - '`drake_cache_log_file`'
  - '`drake_get_session_info`'
  - '`read_drake_seed`'
  - '`show_source`
  - '`file_store`'
- title: Cache cleaning
  contents: 
  - '`clean`'
  - '`drake_gc`'
  - '`rescue_cache`''
- title: Progress
  contents:
  - '`progress`'
  - '`running`'
  - '`failed`'
```
